# help intent
---
type: intent
name: bot_help
slots:
  - name: bot
    entity: bot
utterances:
  - help bots
  - help with [bot](news) bot
  - help with bot
  - help with [bot](loan application)
  - What are bots
  - What is a bot?
  - Tell me about bots
  - What's the [bot](loan application) bot
  - How do I use the [bot](loan application) bot
  - How does the [bot](news) bot work?
  - What is the [bot](news) bot?

# bot info intent
---
type: intent
name: bot_info
slots:
  - name: bot
    entity: bot
utterances:
  - show bots
  - all the bots
  - What bots are there
  - Get bots
  - bots
  - Get the bots
  - Show me the bots
  - Show me the [bot](apply) bot
  - Get the [bot](loan application) bot
  - I want to talk to the [bot](loan application) bot
  - I want to [bot](apply for a loan)

# bot entity
---
type: entity
name: bot
automatically_extensible: no
values:
- news
- email
- [loan application, apply for a loan, apply for loan]
- calendar