# help intent
---
type: intent
name: bot_help
slots:
  - name: bot
    entity: bot
utterances:
  - help bots
  - help with [bot](news) bot
  - help with bot
  - help with [bot](loan application)
  - What are bots
  - What is a bot?
  - Tell me about bots
  - What's the [bot](loan application) bot
  - How do I use the [bot](loan application) bot
  - How does the [bot](news) bot work?
  - What is the [bot](news) bot?

# bot info intent
---
type: intent
name: bot_info
slots:
  - name: bot
    entity: bot
utterances:
  - show bots
  - all the bots
  - What bots are there
  - Get bots
  - bots
  - Get the bots
  - Show me the bots
  - Show me the [bot](apply) bot
  - Get the [bot](loan application) bot
  - I want to talk to the [bot](loan application) bot
  - I want to [bot](apply for a loan)

# bot entity
---
type: entity
name: bot
automatically_extensible: no
values:
- news
- email
- [loan application, apply for a loan, apply for loan]
- calendar

# vish_help intent
---
type: intent
name: vish_help
slots:
  - name: module
    entity: module
utterances:
  - What is vish
  - help vish
  - help vish modules
  - help administer
  - help administer computers
  - help manage computers
  - help with vish [vish_module](openshift) module
  - help with vish modules
  - help with vish [vish_module](openshit)
  - help with [vish_module](openshift) module
  - What are vish modules
  - What is a vish module?
  - Tell me about vish modules
  - What's the [vish_module](openshift) vish module
  - How do I use the vish [vish_module](openshift) module
  - How do I administer [vish_module](openshift) openshift

# vish_info intent
---
type: intent
name: vish_info
slots:
  - name: module
    entity: module
utterances:
  - vish
  - show vish modules
  - all the vish modules
  - What vish modules are there
  - Get vish modules
  - vish modules
  - Get the vish modules
  - Show me the vish modules
  - Show me the [vish_module](openshift) module
  - start vish [vish_module](openshift)
  - vish [vish_module](openshift)
  - I want to manage [vish_module](openshift)
  - openshift [openshift_objects](pods)
  - openshift [openshift_objects](build configs)
  - openshift [openshift_objects](routes)

# vish_module entity
---
type: entity
name: vish_module
automatically_extensible: no
values:
- openshift

# vish_object entity
---
type: entity
name: openshift_objects
automatically_extensible: no
values:
- pods
- build configs
- deployment configs
- routes
- services