kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/evals25-shared-7daa/deploymentconfigs/mongodb
  resourceVersion: '39316895'
  name: mongodb
  uid: 40e7f332-f5f9-11e9-ac88-0a4477eeb22a
  creationTimestamp: '2019-10-24T00:57:29Z'
  generation: 2
  namespace: evals25-shared-7daa
  labels:
    template: mongodb-persistent-template
    template.openshift.io/template-instance-owner: 40e0ce38-f5f9-11e9-ae83-0a647d13a1b4
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - mongodb
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'mongodb:3.2'
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/openshift/mongodb@sha256:e37f9d4bca513c086df07ee3d662806e2b3d927f403237ac963136406e87488e
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    name: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mongodb
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
      containers:
        - resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p
                  $MONGODB_PASSWORD --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: mongodb
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-admin-password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-name
          securityContext:
            capabilities: {}
            privileged: false
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mongodb-data
              mountPath: /var/lib/mongodb/data
          terminationMessagePolicy: File
          image: >-
            docker-registry.default.svc:5000/openshift/mongodb@sha256:e37f9d4bca513c086df07ee3d662806e2b3d927f403237ac963136406e87488e
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 2
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 1
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-10-24T00:58:13Z'
      lastTransitionTime: '2019-10-24T00:58:13Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-10-24T00:58:14Z'
      lastTransitionTime: '2019-10-24T00:58:14Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "mongodb-1" successfully rolled out
  replicas: 1
  readyReplicas: 1
