kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/evals25-shared-7daa/deploymentconfigs/victor-webapi
  resourceVersion: '79901368'
  name: victor-webapi
  uid: 6626725c-feb0-11e9-813c-0a635a9e0dde
  creationTimestamp: '2019-11-04T03:08:39Z'
  generation: 76
  namespace: evals25-shared-7daa
  labels:
    app: victor-webapi
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - victor-webapi
        from:
          kind: ImageStreamTag
          namespace: evals25-shared-7daa
          name: 'victor-webapi:latest'
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/evals25-shared-7daa/victor-webapi@sha256:dfb766b0fb773a1f83d576b7ef0778203f67fa32fed447b9767bb57829d0f190
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    deploymentconfig: victor-webapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: victor-webapi
        deploymentconfig: victor-webapi
    spec:
      containers:
        - name: victor-webapi
          image: >-
            docker-registry.default.svc:5000/evals25-shared-7daa/victor-webapi@sha256:dfb766b0fb773a1f83d576b7ef0778203f67fa32fed447b9767bb57829d0f190
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KIE_SERVER_URL
              value: 'http://172.30.117.184:8080/services/rest/'
            - name: KIE_ADMIN_USER
              value: adminUser
            - name: KIE_ADMIN_PWD
              value: awoLXq1!
            - name: CUI_EDDI_SERVER_URL
              value: 'http://172.30.247.205:7070'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 76
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/evals25-shared-7daa/victor-webapi@sha256:dfb766b0fb773a1f83d576b7ef0778203f67fa32fed447b9767bb57829d0f190
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 75
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-11-04T03:09:17Z'
      lastTransitionTime: '2019-11-04T03:09:17Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-12-06T18:28:10Z'
      lastTransitionTime: '2019-12-06T18:28:08Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "victor-webapi-75" successfully rolled out
  replicas: 1
  readyReplicas: 1
